// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_WindowsLibraryExample_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::WindowsLibraryExample::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::WindowsLibraryExample
{
    MainWindow::MainWindow() :
        MainWindow(make<WindowsLibraryExample::implementation::MainWindow>())
    {
    }
}
