
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::WindowsLibraryExample::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::WindowsLibraryExample::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock TitleTextBlock()
        {
            return _TitleTextBlock;
        }
        void TitleTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _TitleTextBlock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowAlertDialogButton()
        {
            return _ShowAlertDialogButton;
        }
        void ShowAlertDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowAlertDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowFileDialogButton()
        {
            return _ShowFileDialogButton;
        }
        void ShowFileDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowFileDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowMultiFileDialogButton()
        {
            return _ShowMultiFileDialogButton;
        }
        void ShowMultiFileDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowMultiFileDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowFolderDialogButton()
        {
            return _ShowFolderDialogButton;
        }
        void ShowFolderDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowFolderDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowMultiFolderDialogButton()
        {
            return _ShowMultiFolderDialogButton;
        }
        void ShowMultiFolderDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowMultiFolderDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShowSaveFileDialogButton()
        {
            return _ShowSaveFileDialogButton;
        }
        void ShowSaveFileDialogButton(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShowSaveFileDialogButton = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock ResultTextBlock()
        {
            return _ResultTextBlock;
        }
        void ResultTextBlock(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _ResultTextBlock = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _TitleTextBlock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowAlertDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowFileDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowMultiFileDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowFolderDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowMultiFolderDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShowSaveFileDialogButton{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _ResultTextBlock{nullptr};
    };
}

