// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_WindowsLibraryExample_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::WindowsLibraryExample::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::WindowsLibraryExample
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<WindowsLibraryExample::implementation::XamlMetaDataProvider>())
    {
    }
}
