// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_WindowsLibraryExample_0_H
#define WINRT_WindowsLibraryExample_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::WindowsLibraryExample
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::WindowsLibraryExample::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::WindowsLibraryExample::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::WindowsLibraryExample::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::WindowsLibraryExample::MainWindow> = L"WindowsLibraryExample.MainWindow";
    template <> inline constexpr auto& name_v<winrt::WindowsLibraryExample::XamlMetaDataProvider> = L"WindowsLibraryExample.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::WindowsLibraryExample::IMainWindow> = L"WindowsLibraryExample.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::WindowsLibraryExample::IMainWindow>{ 0x6E72A54F,0x8B8C,0x511E,{ 0xB5,0x81,0x91,0x8E,0xD5,0x91,0x0E,0xB7 } }; // 6E72A54F-8B8C-511E-B581-918ED5910EB7
    template <> struct default_interface<winrt::WindowsLibraryExample::MainWindow>{ using type = winrt::WindowsLibraryExample::IMainWindow; };
    template <> struct default_interface<winrt::WindowsLibraryExample::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::WindowsLibraryExample::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_WindowsLibraryExample_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::WindowsLibraryExample::IMainWindow>
    {
        template <typename D> using type = consume_WindowsLibraryExample_IMainWindow<D>;
    };
}
#endif
